### ISSUE TITLE
CRASH - bound must be positive

### ISSUE THREAD

**Issue by Xorbah** [TheMarstonConnell/Better-Slimes#3]
Uploaded the file below. Crashes approximately 30 minutes after server uptime, and refuses to boot up again unless the entire world save is deleted. I've traced it down to this mod. Hope something can get done with it.

[crash-2019-03-14_17.21.36-server (1).txt](https://github.com/TheMarstonConnell/Better-Slimes/files/2969177/crash-2019-03-14_17.21.36-server.1.txt)

**Comment by waluigiisbest99** [comment]
Yes i had this exact same issue except it happened when in the nether or even when i went to the aether via  aether reborn mod. Never happens in the overworld.

**Comment by pupnewfster** [comment]
@TheMarstonConnell someone asked for help in the discord I help run and I believe it is the same crash as this, #1 #4 and #5. (their crash report https://pastebin.com/JxuLd4F2 )

The issue has to do with this [line](https://github.com/TheMarstonConnell/Better-Slimes/blob/master/src/main/java/MICDeps/util/handlers/RegistryHandler.java#L86) where you are generating a random number. The issue has to do with the fact this code is **ONLY** ran if `e.size() < 1` and the JavaDocs for [Random#nextInt(int bound)](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html#nextInt-int-) state that the bound must be at least 1. Given your check ensuring it is less than one whenever this code is reached a crash will happen.

**Comment by TheMarstonConnell** [comment]
Fixed in version 1.2
