### ISSUE TITLE
Crashes the game and keeps crashing when entering world

### ISSUE THREAD

**Issue by dave1505** [TheMarstonConnell/Better-Slimes#4]
The game just crashed randomly in two different times, in both I was riding a boat looking and the shore
After trying to load the save file it kept on crashing, only after 10+atempts removing different mods 
did I remove just this one to finally be able to load the save without a crash, it was certainly the cause

Here's the crash report
https://drive.google.com/open?id=1aHd8Km77Bj6rZKZ4q2czGENSgYkh8trG

**Comment by TheMarstonConnell** [comment]
I cannot see the crash report, please make it on pastebin or gist

**Comment by dave1505** [comment]
https://pastebin.com/yvVy827B

I think I was just able to reproduce it, this time it happened as I was killing a tiny blue slime

**Comment by TheMarstonConnell** [comment]
Fixed in 1.2
