### ISSUE TITLE
Crashing in other dimensions, including modded ones

### ISSUE THREAD

**Issue by waluigiisbest99** [TheMarstonConnell/Better-Slimes#5]
I one day decided to visit the nether after i had required all the resources i need only few minutes in there i noticed lag spikes and then the game crashed, I tried loading the save again crash, so i started to remove mods (kept the old save as a backup) until the removal of better slimes the save wouldn't load again. I have no idea why this would happen. But it corespondent with someone elses issue with the same bound must be positive message.

[crash-2019-07-14_19.16.00-server.txt](https://github.com/TheMarstonConnell/Better-Slimes/files/3394156/crash-2019-07-14_19.16.00-server.txt)

**Comment by TheMarstonConnell** [comment]
Fixed in 1.2
